# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

theme: jekyll-theme-chirpy
theme_mode: dark # [light|dark]
# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock

# 2. Installed Gems
plugins:
- jekyll-paginate

# 3. Gem settings
paginate: 3 # jekyll-paginate > items per page
paginate_path: /page:num # jekyll-paginate > blog page

# 4. Jekyll settings
sass:
  style: compressed # Style compression
excerpt_separator: <!-- more --> # Marks end of excerpt in posts
timezone: Europe/London # Timezone for blog posts and alike

# 5. Collections
collections:
  tabs:
    output: true
    sort_by: order
  # posts:
  #   title: Home # Needed for Siteleaf
  #   output: true
    # description: "This is merely a demo, find out more [about Garth](about)" # The post list page content

# 6. Jekyll collections settings
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
  - scope:
      path: ""
      type: posts
    values:
      layout: post # Default layout
  - scope:
      path: ""          # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true    # Enable comments in posts.
      toc: true         # Display TOC column in posts.
      # DO NOT modify the following parameter unless you are confident enough
      # to update the code of all other post links in this project.
      permalink: /posts/:title/
  - scope:
      path: _drafts
    values:
      comments: false
  - scope:
      path: ""
      type: tabs             # see `site.collections`
    values:
      layout: page
      permalink: /:title/
  - scope:
      path: assets/img/favicons
    values:
      swcache: true
  - scope:
      path: assets/js/dist
    values:
      swcache: true
# 7. Site settings
title: guanerlin
subtitle: The life of a frustrated engineer
email: zhenglin9527@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Life is hard, so as the coding work.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://guanerlin.github.io" # the base hostname & protocol for your site, e.g. http://example.com
social_username: guanerlin
motto: "Stay curious"
encoding: utf-8 # Make sure the encoding is right
# logo: "/assets/logo.svg" # Site logo
favicon: "favicon.ico"
lang: en-GB

#8. tag
tag_page_layout: tag_page
tag_page_dir: tag
tag_feed_layout: tag_feed
tag_feed_dir: tag
tag_permalink_style: pretty

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/


  # comments
  comments:
  active: giscus        # The global switch for posts comments, e.g., 'disqus'.  Keep it empty means disable
  # The active options are as follows:
  disqus:
    shortname:    # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  # utterances settings › https://utteranc.es/
  utterances:
    repo:         # <gh-username>/<repo>
    issue_term:   # < url | pathname | title | ...>
  # Giscus options › https://giscus.app
  giscus:
    repo: techno-tim/techno-tim.github.io
    repo_id: MDEwOlJlcG9zaXRvcnkyNTQ3ODQ3Nzk
    category: Comments
    category_id: DIC_kwDODy-1C84CSN7z
    mapping: pathname          # optional, default to 'pathname'
    input_position: bottom  # optional, default to 'bottom'
    lang: en            # optional, default to the value of `site.lang`
    reactions_enabled: 1
